version: '3'
services:
  db: 
    container_name: db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Thongsongsom@1
      - MYSQL_DATABASE=oclockne_webtest
      - MYSQL_USER=oclockne
      - MYSQL_PASSWORD=Thongsongsom@1
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./DB/:/docker-entrypoint-initdb.d"
     
    restart: always
    ports:
      - "9906:3306"
  server:
    build: ./Server
    ports:
      - "3001:3001"
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - db