version: '3'
services:
  db: 
    container_name: db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Thongsongsom@1
      - MYSQL_DATABASE=oclockne_Webtest
      - MYSQL_USER=oclockne
      - MYSQL_PASSWORD=Thongsongsom@1
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./DB:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - "9906:3306"
  server:
    build: ../../server
    ports:
      - "3001:3001"
    depends_on:
      - db
  client:
    build: ../../client
    ports:
      - "5173:5173"
    depends_on:
      - server
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    restart: always
    depends_on:
      - db