name: Docker Compose Workflow test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        ports:
          - 8080:8080
        options: --entrypoint "bash"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          apt-get update
          apt-get -y install docker-compose

      - name: Build and run Docker Compose services
        run: |
          docker-compose up -d

      - name: Run tests (Replace with your test command)
        run: |
          cd path/to/your/project
          npm install
          npm test

      - name: Stop Docker Compose services
        run: |
          docker-compose down
